# Clone, build, and deploy, restarting Nginx if necessary. This playbook must
# be run after provisioning, and is used to deploy and build the specified
# commit (overridable via extra vars) on the server.

- hosts: all
  become: yes
  become_method: sudo
  vars:
    commit: master
    force: false
  roles:
    - deploy
