# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: generate build info file
  template: src=build_info.txt dest={{clone_path}}/{{build_info_path}}
  when: build_info_path is defined
